# Generated by Django 5.0.2 on 2024-03-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
