# Generated by Django 5.0.2 on 2024-03-07 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0006_alter_response_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.choice'),
        ),
    ]
