# Generated by Django 5.0.2 on 2024-03-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0008_response_answer_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
